name: 'My First GitHub Actions Workflow'

on: push

jobs:
  first-job:
    name: 'First Job'

    strategy:
      matrix:
        os: [ 'windows-latest', 'macos-latest', 'ubuntu-latest' ]
        nodejs: ['14.x', '16.x']
    runs-on: ${{ matrix.os }}

    steps:
    - name: 'Setup node.js version'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.nodejs}}

    - name: 'Check node.js version on ${{matrix.os}}'
      shell: bash
      run: |
        echo "nodejs version: $(node --version)"