name: 'My First GitHub Actions Workflow'

on: push

jobs:
  first-job:
    name: 'First Job'

    runs-on: windows-latest

    steps:
    - name: Mask output value
      id: first
      shell: bash
      run: |
        first_value="This is first value"
        echo "::add-mask::$first_value"
        echo "::set-output name=first_value::$first_value"

    - name: Check output value
      shell: bash
      run: |
        echo "first value: ${{ steps.first.outputs.first_value }}"