name: 'My First GitHub Actions Workflow'

on: push

jobs:
  first-job:
    name: 'First Job'

    runs-on: windows-latest

    steps:
    - name: OCA Power first job
      shell: bash
      run: |
        echo "OCA Power from first job"

  second-job:
    name: 'Second Job'
    needs: first-job

    runs-on: ubuntu-latest

    steps:
    - name: OCA Power second job
      shell: bash
      run: |
        echo "OCA Power second job"