name: 'My First GitHub Actions Workflow'

on: push

jobs:
  first-job:
    name: 'First Job'

    strategy:
      matrix:
        os: [ 'windows-latest', 'macos-latest', 'ubuntu-latest' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: OCA Power from ${{ matrix.os }} 1
      shell: bash
      run: |
        echo "OCA Power on ${{ matrix.os }} 1"

    - name: OCA Power from ${{ matrix.os }} 2
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        echo "OCA Power on ${{ matrix.os }} 2"